name: Build Countdown Speedhack Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Xcode Environment
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Compile Speedhack Dylib
        run: |
          clang -dynamiclib \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -arch arm64 \
          -miphoneos-version-min=14.0 \
          -fobjc-arc \
          -Wno-deprecated-declarations \
          Speedhack.m \
          -framework Foundation -framework UIKit -framework CoreFoundation \
          -o Speedhack.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Speedhack-dylib
          path: Speedhack.dylib
          retention-days: 7
